### ISSUE TITLE
readme doc unclear or wrong on array notation for t()

### ISSUE THREAD

**Issue by kairos666** [lukeed/rosetta#12]
Great library simple and flexible.

Small issue I've found, using the readme doc notation doesn't work for me
**a string that with dot notation — `'foo.bar[1].baz'`**

from the tests I think the correct syntax should be `'foo.bar.1.baz'`. Unless of course you can help me correct my understanding of this case.

Cheers

**Comment by lukeed** [comment]
Oh, whoops! Yes only `foo.bar.1.baz` notation is supported for string keys. If you want to use an array-key, you could do this too: `['foo', 'bar', 1, 'baz']` (note: `1` or `'1'` both work here).
