### ISSUE TITLE
Add Next.js example to readme

### ISSUE THREAD

**Issue by StarpTech** [lukeed/rosetta#2]
Would you be interested? https://github.com/zeit/next.js/pull/11841

**Comment by lukeed** [comment]
I'll link to it as a "recipe" once it lands.

Thank you for taking the time to do that :)

**Comment by StarpTech** [comment]
It landed https://github.com/zeit/next.js/tree/canary/examples/with-i18n-rosetta

**Comment by lukeed** [comment]
Thanks again!
