### ISSUE TITLE
Current language

### ISSUE THREAD

**Issue by AugustoConti** [lukeed/rosetta#9]
Hi :hand:!

How can I know the current language?

**Comment by lukeed** [comment]
Hey, there wasn't a way 😅 Adding it now.

**Comment by AugustoConti** [comment]
Thank you! :clap:

**Comment by lukeed** [comment]
No problem :) Available in `rosetta@1.1.0` via `locale()` without an argument. Also added `table(lang)` which will give you the full dictionary/table for a lang code.
